apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: team1
spec:
  type: ClusterIP
  ports:
  - name: "vote-service"
    port: 80
    targetPort: 80
  selector:
    app: vote
  
